<?php

/**
 * @file
 * Domain theme Switcher.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function styling_profiles_domain_switch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'styling_profiles_domain_switch.domain_profile':
      $output = t('<p>Find the list of domains and select the styling profile against each domain.
          You may select the profile corresponding to each domain and if you leave
          them blank then default profile will load.</p>');
      return $output;
  }
}
